# trigger: none
# name: $(Test_Major_No).$(Test_Minor_No).$(Test_Sprint_No).$(rev:r)  

resources:
  repositories:
    - repository: Repo
      name: Project/Repo
      type: git
      ref: Test
      trigger:
        branches:
          include:
          - refs/heads/Test
# variables:
#   - template: ../Variables/SharedVars_BE.yml 
#   - template: ../Variables/Test_AppSettings.yml 


jobs:
  - job: 'Job1'  
    displayName: 'Change Work Item States'
    timeoutInMinutes: 15
    cancelTimeoutInMinutes: 1
    pool:
      name: CheckAgents

    steps:
    - checkout: none 

    - template: ChangeWorkItemStates.yml
      parameters:
        RepoName: Repo
        BranchName: Test
        ItemState: "Test Released"
    
